name: .NET Core CI/CD

on: [push, pull_request]

jobs:
  test:
    name: xUnit test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet-version: [3.1]
    env: 
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      NUGET_XMLDOC_MODE: skip

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/.nuget/packages
        key: nuget-${{ matrix.os }}-${{ matrix.dotnet-version }}
        restore-keys: |
          nuget-${{ matrix.os }}-
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Build
      run: dotnet Build -c Debug
    - name: Test
      working-directory: ./Test
      run: dotnet test --verbosity normal -c Debug --no-build

  dotnet-publish:
    if: contains(github.ref, 'tags/v')
    needs: [test]
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        dotnet-version: [3.1]
    runs-on: ${{ matrix.os }}
    env: 
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      NUGET_XMLDOC_MODE: skip
    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: nuget-${{ matrix.os }}-${{ matrix.dotnet-version }}
          restore-keys: |
            nuget-${{ matrix.os }}-
            
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - name: vars
        id: vars
        run: |
          echo ::set-output name=runtime_id::"$(echo ${{ matrix.os }} | sed 's/windows/win/g;s/ubuntu/linux/g;s/macOS/osx/g;s/latest/x64/g')"
          echo ::set-output name=version::${TAG_REF_NAME##*/v}
        env:
          TAG_REF_NAME: ${{ github.ref }}
        
      - name: dotnet publish
        run: |
          dotnet publish --self-contained true -r ${{ steps.vars.outputs.runtime_id }} -c Release -o ${{ steps.vars.outputs.runtime_id }} -p:Version=${{ steps.vars.outputs.version }}
          zip -r ${{ steps.vars.outputs.runtime_id }} ${{ steps.vars.outputs.runtime_id }}
      
      - name: Upload zip archive
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.vars.outputs.runtime_id }}
          path: ${{ steps.vars.outputs.runtime_id }}.zip

  create-releases:
    name: Create GitHub Release
    if: contains(github.ref, 'tags/v')
    needs: [test, dotnet-publish]
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        
      - name: Output Release URL File
        run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
        
      - name: Save Release URL File for publish
        uses: actions/upload-artifact@v1
        with:
          name: release_url
          path: release_url.txt
    
  upload-release:
    name: Upload artifacts to GitHub Release
    if: contains(github.ref, 'tags/v')
    strategy:
      matrix:
        runtime_id: [win-x64, linux-x64, osx-x64]
    runs-on: ubuntu-latest
    needs: [test, dotnet-publish, create-releases]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.runtime_id }}
          path: ${{ matrix.runtime_id }}.zip

      - uses: actions/download-artifact@v2
        with:
          name: release_url
      
      - name: Get Release Info
        id: get_release_info
        run: |
          echo ::set-output name=file_name::${REPOSITORY_NAME##*/}-${TAG_REF_NAME##*/v}
          value=`cat release_url/release_url.txt`
          echo ::set-output name=upload_url::$value
          echo ::set-output name=version::${TAG_REF_NAME##*/v}
        env:
          TAG_REF_NAME: ${{ github.ref }}
          REPOSITORY_NAME: ${{ github.repository }}
      
      - name: Upload assets to GitHub Release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: ./${{ matrix.rid }}.zip
          asset_name: ${{ steps.get_release_info.outputs.file_name }}-${{ matrix.rid }}-core${{ matrix.dotnet-version }}.zip
          asset_content_type: application/zip      
      
      
      
