name: .NET Core CI/CD

on: [push, pull_request]

jobs:
  test:
    name: xUnit test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet-version: [3.1]
    env: 
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      NUGET_XMLDOC_MODE: skip

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/.nuget/packages
        key: nuget-${{ matrix.os }}-${{ matrix.dotnet-version }}
        restore-keys: |
          nuget-${{ matrix.os }}-
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Test
      working-directory: ./Test
      run: dotnet test --verbosity normal -c Debug
